spin_manifest_version = 2

[application]
name = "mstd-newspenguin-rss"
version = "0.0.1"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = "https://mstd.seungjin.net/@newspenguin"

[variables]
internal_key = { required = true }
newspenguin_rss_uri = { required = true }
newspenguin_mstd_api_uri = { required = true }
newspenguin_mstd_access_token = { required = true }

[[trigger.cron]]
component = "newspenguin-rss"
cron_expression = "*/10 * * * * *"

[component.newspenguin-rss]
source = "target/wasm32-wasip1/release/newspenguin_rss.wasm"
sqlite_databases = ["lachuoi"]
allowed_outbound_hosts = [
  "https://www.newspenguin.com",
  "https://mstd.seungjin.net",
]

[component.newspenguin-rss.variables]
rss_uri = "{{ newspenguin_rss_uri }}"
mstd_api_uri = "{{ newspenguin_mstd_api_uri }}"
mstd_access_token = "{{ newspenguin_mstd_access_token }}"

[component.newspenguin-rss.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
